using Godot;
using System;

public class Enums
{
    public enum AreaShape
    {
        None = 0,
        Point = 1,
        Circle = 2,
        Cross = 3,
        T = 4,
        Ring = 5,
        Rectangle = 6,
        RectRing = 7,
        FreePointsForm = 8,
        Ti = 9,
        DirectedRectangle = 10,
        Empty = 32767
    }

    public enum TriggerType
    {
        None = 0,
        HpGain = 1,
        HpLoss = 2,
        HpBuff = 3,
        HpDebuff = 4,
        HpLossFire = 5,
        HpLossWater = 6,
        HpLossWind = 7,
        HpLossEarth = 8,
        HpLeechFire = 9,
        HpLeechWater = 10,
        HpLeechWind = 11,
        HpLeechEarth = 12,
        HpLeech = 13,
        HpLossFromSpell = 14,
        Poison = 15,
        ApGain = 51,
        ApLoss = 52,
        ApBuff = 53,
        ApDebuff = 54,
        ApUse = 55,
        ApLeech = 56,
        ResApChange = 57,
        MpGain = 61,
        MpLoss = 62,
        MpBuff = 63,
        MpDebuff = 64,
        MpUse = 65,
        ResMpChange = 66,
        MpLeech = 67,
        ResGain = 71,
        ResLoss = 72,
        ResWaterGain = 81,
        ResWaterLoss = 82,
        ResEarthGain = 91,
        ResEarthLoss = 92,
        ResWindGain = 101,
        ResWindLoss = 102,
        ResFireGain = 111,
        ResFireLoss = 112,
        DmgGain = 121,
        DmgLoss = 122,
        DmgWaterGain = 131,
        DmgWaterLoss = 132,
        DmgEarthGain = 141,
        DmgEarthLoss = 142,
        DmgWindGain = 151,
        DmgWindLoss = 152,
        DmgFireGain = 161,
        DmgFireLoss = 162,
        InitBuff = 171,
        InitDebuff = 172,
        HealGain = 181,
        HealLoss = 182,
        TackleGain = 201,
        TackleLoss = 202,
        DodgeGain = 211,
        DodgeLoss = 212,
        Debuff = 221,
        CastSpell = 222,
        Death = 223,
        UsableUsed = 224,
        TurnStart = 1001,
        TurnEnd = 1002,
        GlobalTurnStart = 1003,
        GlobalTurnEnd = 1004,
        Delayed = 2001,
        RevealInvisible = 5001,
        TurnStartOnCell = 10000,
        EnterArea = 10001,
        LeaveArea = 10002,
        LaunchSpellOnArea = 10003,
        FighterOnItWhenCast = 10006,
        MoveInsideArea = 10008,
        UnapplyArea = 10010,
        ExecutionLimitReached = 10011
    }

    public enum TargetType : long
    {
        Always = 0,
        InAoe = 1,
        IsCaster = 1L << 1,
        IsAlly = 1L << 2,
        IsEnemy = 1L << 3,
        IsNotSummoned = 1L << 4,
        IsSummoned = 1L << 5,
        IsEffectArea = 1L << 6,
        IsAllyExceptCaster = 1L << 7,
        IsNotCaster = 1L << 8,
        IsNotHuman = 1L << 9,
        IsHuman = 1L << 10,
        ZobalMaskClass = 1L << 11,
        ZobalMaskCoward = 1L << 12,
        ZobalMaskBerzerk = 1L << 13,
        IsKo = 1L << 14,
        BreedFeca = 1L << 16,
        BreedOsamodas = 1L << 17,
        BreedEnutrof = 1L << 18,
        BreedSram = 1L << 19,
        BreedXelor = 1L << 20,
        BreedEcaflip = 1L << 21,
        BreedEniripsa = 1L << 22,
        BreedIop = 1L << 23,
        BreedCra = 1L << 24,
        BreedSadida = 1L << 25,
        BreedSacrier = 1L << 26,
        BreedPandawa = 1L << 27,
        BreedRoublard = 1L << 28,
        BreedZobal = 1L << 29,
        BreedNotFeca = 1L << 32,
        BreedNotOsamodas = 1L << 33,
        BreedNotEnutrof = 1L << 34,
        BreedNotSram = 1L << 35,
        BreedNotXelor = 1L << 36,
        BreedNotEcaflip = 1L << 37,
        BreedNotEniripsa = 1L << 38,
        BreedNotIop = 1L << 39,
        BreedNotCra = 1L << 40,
        BreedNotSadida = 1L << 41,
        BreedNotSacrier = 1L << 42,
        BreedNotPandawa = 1L << 43,
        BreedNotRoublard = 1L << 44,
        BreedNotZobal = 1L << 45,
        SameBreed = 1L << 47,
        NotImmune = 1L << 48,
        NotIntransposable = 1L << 49,
        NotStabilized = 1L << 50,
        NotRooted = 1L << 51,
        NotFullLife = 1L << 52,
        NotImmuneApLoss = 1L << 53,
        NotImmuneMpLoss = 1L << 54,
        ImmuneToSpells = 1L << 55,
        NotImmobilized = 1L << 56,
        NotPetrified = 1L << 57,
        ResistantToEarthDamage = 1L << 58,
        ResistantToWindDamage = 1L << 59,
        ResistantToWaterDamage = 1L << 60,
        ResistantToFireDamage = 1L << 61,
        EffectArea = 1L << 62
    }

    public enum Breeds
    {
        Feca = 1,
        Osamodas = 2,
        Enutrof = 3,
        Sram = 4,
        Xelor = 5,
        Ecaflip = 6,
        Eniripsa = 7,
        Iop = 8,
        Cra = 9,
        Sadida = 10,
        Sacrieur = 11,
        Pandawa = 12,
        Roublard = 13,
        Zobal = 14,
        Steamer = 15,
        Eliotrope = 16,
        Huppermage = 17,
        Ouginak = 18,
        Forgelance = 19,
    }

    public enum SphereType
    {
        Minor = 0,
        Major = 1,
        Key = 2,
    }
}
